# Generated by Django 4.2.4 on 2023-08-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_vendor'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='customers',
            field=models.ManyToManyField(related_name='customers', to='customer.customer'),
        ),
    ]
