# Generated by Django 4.2.4 on 2023-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='description',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
