# Generated by Django 4.2.4 on 2023-09-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_customer_vendor'),
        ('discounts', '0002_discount_customers'),
        ('inventory', '0002_alter_product_id'),
        ('cart', '0002_shoppingcart_description_shoppingcart_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cart.shoppingcart')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_to_customer', to='customer.customer')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='discounts.discount')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.product')),
            ],
        ),
    ]
